// Apache 2.0 Jackson Creative.

#ifndef BLACKJACK_FUNCTIONS_H
#define BLACKJACK_FUNCTIONS_H

// Include necessary modules:
#include <iostream>
#include <cstdlib>
#include <ctime>
#include <cstring>
#include <cmath> // Surprise tool that'll help us later.
#include "blackjackCodes.h"
#include "blackjackCards.h"g 
using std::cout;
using std::cin;
using std::endl;
using std::rand;
using std::srand;
using std::string;

// Seed the random generator.
const string suites[4] = { "Clubs", "Diamonds", "Hearts", "Spades" };
const int cardNumbers[13] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 }; // Type King Queen Jack.

/** givePlayerCard
 * This function generates a random card and gives it to the player.
 * This function has no parameters.
 * This function returns the random card generated by the function.
*/
int giveCardPlayer() {
 int cards = rand() % 13;
 int randCard = cardNumbers[cards];
 return randCard;
};

/** giveDealerCard
 * This function generates a random card and gives it to the dealer.
 * This function has no parameters.
 * This function returns the random card generated by the function.
*/
int giveCardDealer() {
    int cards = rand() % 13;
    int randCard = cardNumbers[cards];
    return randCard;
}

/** randomSuite
 * This function generates a random suite and assigns it to the card (i.e. 2 of Spades).
 * This function has no parameters.
 * This function returns the random suite generated by the function.
*/

string randomSuite() {
  int randomSuites = rand() % 4;
  return suites[rand() % 4];
}

/** formatCards
 * This function formats cards to match a random suite (i.e. Two of Hearts)
 * This function has two parameters. [cardsToFormat: The card value. suite: The suite.]
 * This function returns the random suite generated by the function.
*/
int formatCards(int cardsToFormat, string suite) {
    cout << "You were given a: " << cardsToFormat << " of " << suite << endl;
}

/** checkBlackjack
 * This function checks for blackjack for the dealer and the player. 
 * This function has two parameters. [Card Count for player and card count for dealer.]
 * This function returns the random suite generated by the function.
*/

int checkBlackjack(int playerCards, int dealerCards) {
    if(playerCards == 21) {
        return PLAYER_BLACKJACK;
    } else if(dealerCards == 21) {
       return DEALER_BLACKJACK;
    }

    return 0;
}
/** checkBust
 * This function checks for a bust.
 * This function has two parameters.
 * This function returns a code for PLAYER_BUST and DEALER_BUST.
*/
int checkBust(int playerCards, int dealerCards) {
    if(playerCards > 21) {
        return PLAYER_BUST;
    } else if(dealerCards > 21) {
       return DEALER_BUST;
    }
    return 0;
}

/** endGame
 * This function exits the program.
*/

int endGame() { 
    return END_GAME;
    exit(true);
}

#endif